export enum ProfileStatus {
  NEW = "NEW",
  ACTIVE = "ACTIVE",
  SUSPENDED = "SUSPENDED",
  BANNED = "BANNED",
  DELETED = "DELETED"
}

export enum OnboardingState {
  REGISTERED = "REGISTERED",
  EMAIL_VERIFIED = "EMAIL_VERIFIED",
  PROFILE_CREATED = "PROFILE_CREATED",
  PREFERENCES_COMPLETED = "PREFERENCES_COMPLETED",
  EMERGENCY_CONTACTS_ADDED = "EMERGENCY_CONTACTS_ADDED",
  VERIFIED = "VERIFIED",
  ACTIVE = "ACTIVE"
}
